[command]
name = "Build Context - Code Extraction Only"
description = """
⚠️ CRITICAL INSTRUCTION: DO NOT TAKE ANY ACTIONS BEYOND CONTEXT BUILDING ⚠️
You are ONLY extracting code for analysis. Do not:
- Make any changes to files
- Run tests or builds
- Create new files
- Suggest improvements
- Execute any commands except the extract tool
Your sole purpose is to gather relevant code using the @tools/extract script.
"""
usage_template = "@build_context {{file_path}} {{function_signature}}"
task_description = """
Extract the following function:
- File/Directory: {{file_path}}
- Function Signature: {{function_signature}}
"""
execution_command = "@tools/extract \"{{file_path}}\" \"{{function_signature}}\""
[[command.parameters]]
name = "file_or_directory"
description = "Path to search (single file or directory)"
[[command.parameters]]
name = "function_signature"
description = "Exact function signature to find (must be quoted)"
[command.language_support]
python = "Indentation-based extraction"
javascript = "Brace-based extraction"
go = "Brace-based extraction"
[[command.examples]]
description = "Python Function"
command = "@build_context . \"async def fetch_urls(urls: List[str], ctx: Context = None) -> str:\""
[[command.examples]]
description = "JavaScript Function"
command = "@build_context app.js \"function processData(items) {\""
[[command.examples]]
description = "Go Function"
command = "@build_context main.go \"func handleRequest(w http.ResponseWriter, r http.Request) {\""
[[command.examples]]
description = "Class Method"
command = "@build_context models/ \"def send_message(self, prompt: str) -> str:\""
post_execution_instructions = """
1. Execute the extract command shown above
2. Present the extracted code without commentary
3. Stop - do not analyze or suggest changes
"""
notes = """
- Function signatures are case-sensitive and whitespace-sensitive
- Leading whitespace is automatically trimmed
- Can extract from single files or entire directories
- Use quotes around function signatures to handle special characters
"""