Loaded cached credentials.
```toml
name = "Build Context - Code Extraction Only"
description = """
You are ONLY extracting code for analysis. Do not:
- Make any changes to files
- Run tests or builds
- Create new files
- Suggest improvements
- Execute any commands except the extract tool

Your sole purpose is to gather relevant code using the @tools/extract script.
"""

usage = "@build_context {{file_path}} {{function_signature}}"

execute = "@tools/extract \"{{file_path}}\" \"{{function_signature}}\""

[parameters.file_or_directory]
description = "Path to search (single file or directory)"
type = "string"

[parameters.function_signature]
description = "Exact function signature to find (must be quoted)"
type = "string"

[language_support]
python = "Indentation-based extraction"
javascript = "Brace-based extraction"
go = "Brace-based extraction"

[examples.python_function]
command = "@build_context . \"async def fetch_urls(urls: List[str], ctx: Context = None) -> str:\""

[examples.javascript_function]
command = "@build_context app.js \"function processData(items) {\""

[examples.go_function]
command = "@build_context main.go \"func handleRequest(w http.ResponseWriter, r *http.Request) {\""

[examples.class_method]
command = "@build_context models/ \"def send_message(self, prompt: str) -> str:\""

[notes]
signature_sensitivity = "Function signatures are case-sensitive and whitespace-sensitive"
whitespace_trimming = "Leading whitespace is automatically trimmed"
scope = "Can extract from single files or entire directories"
quoting = "Use quotes around function signatures to handle special characters"
```