name = "Create Golang structs from API documentation for requests and responses"
description = """
This command facilitates the creation of Golang structs from API documentation.
It involves two phases:
Phase 1: Documentation Extraction
- Calls the provided URL using the `get_docs` tool to fetch content.
- Intelligently extracts documentation for the requested section using Gemini 2.5 Flash Preview.
- Returns the relevant documentation as clean, readable text.
This phase is best for:
- API documentation extraction
- Function/method documentation
- Specific topic documentation from larger pages
- Technical documentation that needs focused extraction
Phase 2: Golang Struct Generation
After extracting the JSON structure from Phase 1, the tool will automatically:
1. Identify all objects in the JSON.
2. Determine appropriate Golang types for each field.
3. Create properly formatted structs with JSON tags.
4. Handle nested objects and arrays properly and idiomatically per best practice in Golang.
5. Follow Go naming conventions.
6. Add helpful comments.
7. Ensure that if there are potential null values in the JSON (per the documentation) that we appropriately handle those with Golang pointers.
[parameters.url]
description = "The URL of the documentation page."
type = "string"
[parameters.extract_value]
description = "The specific section/function/topic to extract."
type = "string"
tool_code = """
"""
print(default_api.get_docs(url = "parameters.url, extract_value=parameters.extract_value))"
"""
example_usage = """
create_go_structs "https://developer.tastytrade.com/api-guides/customer-account-info/" "the exact json response for getting customer accounts"
"""
"""
"""