purpose = "Using the additional content designated in the content tags, we want to update env.go with the additional configuration elements."
instructions = [
    "Read the .env file located in the project root folder"
    "Read the env.go file to understand how we want to load the configuration from the .env file into a Configuration golang struct"
    "THEN: look at the content provided within the content tags and update env.go to support the additional configuration"
    "AFTER updating env.go please read internal/config/env_test.go and update the tests to support the additional configuration"
    "Please do not use any external libraries or packages for the actual testing."
]
content = "$ARGUMENTS"