title = "Ultra Diff Review"
purpose = """We want to conduct a thorough comprehensive code review using the appropriate diff approach."
Given the following instructions, execute each task in the order given.
Within each task, execute each instruction in order."""
[[instructions]]
task_title = "## Task 1: Create diff.md"
instructions = [
"Create a new file called diff.md in the root of the project"
"""At the top of the file, add the following markdown:"
"""
# Code Review:
]
- Review the diff, report on issues, bugs and improvements.
- End with a concise markdown table of any issues found, their solutions and a risk
assessment for each issue if applicable
- Use emojis to convey the severity of each issue
## Diff
]
[[instructions]]
task_title = "## Task 2: git diff and append"
instructions = [
"""Run the following command and make sure there is a result:"
git diff --staged
"""IF there is a result: Run the following command to get the diff "
and append it to the diff.md file:
git diff --staged >> diff.md
]