Loaded cached credentials.
```toml
title = "Ultra Diff Review"
purpose = "We want to conduct a thorough comprehensive code review using the appropriate diff approach.\nGiven the following instructions, execute each task in the order given.\nWithin each task, execute each instruction in order."

[[instructions.task]]
name = "Task 1: Create diff.md"

  [[instructions.task.instruction]]
  description = "Create a new file called diff.md in the root of the project"

  [[instructions.task.instruction]]
  description = """At the top of the file, add the following markdown:

```md
# Code Review:  
- Review the diff, report on issues, bugs and improvements.  
- End with a concise markdown table of any issues found, their solutions and a risk
assessment for each issue if applicable
- Use emojis to convey the severity of each issue

## Diff

```"""

[[instructions.task]]
name = "Task 2: git diff and append"

  [[instructions.task.instruction]]
  description = "Run the following command and make sure there is a result:"
  command = "git diff --staged"

  [[instructions.task.instruction]]
  description = "IF there is a result: Run the following command to get the diff and append it to the diff.md file:"
  command = "git diff --staged >> diff.md"
```