Loaded cached credentials.
```toml
purpose = "Prime the context window with the area of the project that we want the model to focus on and understand."

content = "{{content}}"

instructions = [
    "Read the README.md in this directory {{directory}}",
    "Read the Claude.md in this directory {{directory}}",
    "THEN: run git ls-files from this directory {{directory}} to understand the context of the project",
    "THEN: Please focus on the content provided in the content variable"
]
```