Loaded cached credentials.
```toml
[command]
name = "read_file_and_display"
description = "Reads the content of a specified file and displays it without further action."

[command.parameters]
file_name = { type = "string", description = "The absolute path to the file to read." }

[command.instructions]
only_use_read_tool = true
no_edits_or_changes = true
no_new_files = true
no_commands = true
no_analysis_or_comments = true
simply_read_and_display = true
stop_immediately_after_reading = true

[command.tool_code]
code = """
print(default_api.read_file(absolute_path=file_name))
"""
```