Loaded cached credentials.
```toml
name = "Copy to Clipboard Tool"
description = "This command helps you copy various types of content to the system clipboard using the MCP `copy_clipboard` tool."

[tool_definition]
name = "mcp__collect__copy_clipboard"
description = "Copy text to the system clipboard"
parameters = [
    { name = "text", type = "str", description = "The text to copy to the system clipboard" }
]

[usage_instructions]
description = "Use the `mcp__collect__copy_clipboard` tool to copy content based on the user's request from `$ARGUMENTS`."

[common_use_cases]
items = [
    "Code Snippets: Copy formatted code blocks",
    "Configuration: Copy config files, environment variables, or settings",
    "Documentation: Copy markdown, text, or formatted content",
    "Data: Copy JSON, CSV, or other structured data",
    "URLs/Links: Copy lists of URLs or reference links",
    "Command Output: Copy results from previous operations"
]

[best_practices]
items = [
    "Format appropriately: Ensure text is properly formatted for the intended use",
    "Include context: Add comments or headers when helpful",
    "Validate content: Check that sensitive information is not included",
    "Optimize for paste destination: Consider where the user will paste the content"
]

[[example_workflows]]
description = "Copy code with context:"
code = """# Configuration for Production Environment
DATABASE_URL=postgresql://user:pass@host:5432/db
API_KEY=your-api-key-here
DEBUG=false"""

[[example_workflows]]
description = "Copy structured data:"
code = """{
  "urls": [
    "https://example.com/api/endpoint1",
    "https://example.com/api/endpoint2"
  ],
  "headers": {
    "Authorization": "Bearer token",
    "Content-Type": "application/json"
  }
}"""

[task]
description = "Based on the user's request in `$ARGUMENTS`, use the `mcp__collect__copy_clipboard` tool to copy the appropriate content to their system clipboard. Ensure the content is well-formatted and ready for their intended use."
```