name = "Extract Documentation from URLs"
description = "Use the `get_docs` MCP tool to extract specific documentation sections from web pages using Gemini 2.5 Flash."
[details]
what_it_does = """
This tool:
1. Fetches content from the specified URL
2. Uses Gemini 2.5 Flash Preview to intelligently extract documentation for the requested section
3. Returns the relevant documentation as clean, readable text
best_for = [
"API documentation extraction"
"Function/method documentation"
"Specific topic documentation from larger pages"
"Technical documentation that needs focused extraction"
]
[template]
command = "get_docs($ARGUMENTS[0], $ARGUMENTS[1])"
[[arguments]]
name = "url"
description = "The URL of the documentation page"
index = 0
[[arguments]]
name = "extract_value"
description = "The specific section/function/topic to extract"
index = 1
[[examples]]
description = "Extract Python json.dumps documentation:"
command = "get_docs(\"https://docs.python.org/3/library/json.html\", \"json.dumps\")"
[[examples]]
description = "Extract React useEffect documentation:"
command = "get_docs(\"https://react.dev/reference/react/useEffect\", \"useEffect\")"
[[examples]]
description = "Extract specific AWS service documentation:"
command = "get_docs(\"https://docs.aws.amazon.com/s3/latest/userguide/\", \"bucket policies\")"
"""